"""
schemas.py

Core domain models for agent communication. 
Purpose: We define these so our core application NEVER touches provider-specific 
JSON (like OpenAI's or Anthropic's exact dictionary formats). If a provider changes 
their API, we only update the adapter, while this file and our core app remain untouched.
"""

from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class Role(str, Enum):
    """
    Defines who is speaking in the conversation.
    Purpose: Using an Enum prevents bugs from string typos (e.g., typing "assitant" instead of "assistant").
    """
    SYSTEM = "system"       # High-level instructions defining the agent's behavior and rules.
    USER = "user"           # The human typing in the CLI REPL.
    ASSISTANT = "assistant" # The LLM's responses.
    TOOL = "tool"           # The output of a function/tool being returned back to the LLM.

class FinishReason(str, Enum):
    """
    Why did the LLM stop generating text?
    Purpose: This is the traffic light for your Finite State Machine (FSM). 
    It tells your main loop what to do next.
    """
    STOP = "stop"                  # Natural completion. The FSM can print the output and wait for the user.
    LENGTH = "length"              # The model hit the max_tokens limit before finishing.
    TOOL_CALLS = "tool_calls"      # The model paused to ask us to run a tool. The FSM must execute it.
    ERROR = "error"                # Upstream API failure (e.g., safety filter triggered).

# --- Tool Call Definitions ---

class ToolCall(BaseModel):
    """
    Represents a specific request from the LLM to execute a tool.
    Purpose: Normalizes how different models ask for tools.
    """
    id: str                        # Unique ID for this specific call (required to map the result back later).
    name: str                      # The name of the Python function to execute (e.g., "read_file").
    arguments: Dict[str, Any]      # The arguments the LLM wants to pass to the function, parsed as a dictionary.

class ToolDefinition(BaseModel):
    """
    Represents the blueprint of a tool we send TO the LLM so it knows what it can do.
    Purpose: Acts as the contract between your Python skills folder and the LLM.
    """
    name: str                      # Function name.
    description: str               # Crucial: The LLM reads this to decide WHEN to use the tool.
    parameters: Dict[str, Any]     # The JSON Schema dict defining the required arguments and their types.

# --- Standardized Messages ---

class Message(BaseModel):
    """
    Base message protocol.
    Purpose: Enforces that every message in our history list has a role and content.
    """
    role: Role                     # Who sent the message.
    content: Optional[str] = None  # The text content. (Optional because sometimes an assistant message only contains tool calls, no text).

class SystemMessage(Message):
    role: Role = Role.SYSTEM       # Forces the role to be SYSTEM.

class UserMessage(Message):
    role: Role = Role.USER         # Forces the role to be USER.

class AssistantMessage(Message):
    """
    The LLM's response.
    Purpose: Needs to capture both the text it spoke AND any tools it decided to call.
    """
    role: Role = Role.ASSISTANT
    tool_calls: Optional[List[ToolCall]] = Field(default_factory=list) # List of tools it wants us to run.

class ToolResultMessage(Message):
    """
    The data we send back to the LLM after running the tool it asked for.
    Purpose: Closes the loop. The LLM needs the `tool_call_id` to know which request this answer belongs to.
    """
    role: Role = Role.TOOL
    tool_call_id: str              # Must exactly match the ID from the ToolCall object.

# --- Telemetry & Responses ---

class UsageMetrics(BaseModel):
    """
    Tracks token consumption.
    Purpose: You will use this data in Phase 3 (Token Budgeter) to trigger memory compaction when context gets too full, and to calculate API costs.
    """
    prompt_tokens: int = 0         # Tokens consumed by the input history and system prompt.
    completion_tokens: int = 0     # Tokens generated by the model in this turn.
    total_tokens: int = 0          # The sum of both.

class ModelResponse(BaseModel):
    """
    The final payload returned by a ModelDriver after a full generation turn.
    Purpose: No matter if OpenAI or Anthropic is used, your core app receives this exact predictable object.
    """
    message: AssistantMessage      # What the model said / requested.
    usage: UsageMetrics            # How much it cost.
    finish_reason: FinishReason    # What the app should do next.
    
class StreamChunk(BaseModel):
    """
    Used for yielding real-time data to the terminal while the LLM is still typing.
    Purpose: Prevents the CLI from freezing for 10 seconds while waiting for a long answer.
    """
    text_delta: Optional[str] = None # A few characters/words of the response as they stream in.
    reasoning_delta: Optional[str] = None # (Advanced) Used if the model streams its internal reasoning step-by-step. Internal planning and logic (Chain-of-Thought).
    tool_call_delta: Optional[Dict[str, Any]] = None # (Advanced) Used if the model streams its tool arguments JSON chunk-by-chunk.